blog/urls.py
# -*- coding = utf-8 -*-
# @Time : 2024/10/29 15:47
# @Author : Cat_E
# @File : urls.py
# @Software : PyCharm


from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('jingang', views.index, name='index'),
    path('blog/<int:blog_id>', views.blog_detail, name='blog_detail'),
    path('blog/pub', views.pub_blog, name='pub_blog'),
]

ggbk/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.indexjingang, name="indexjingang"),
    path('', include('blog.urls')),
    path('auth/', include('xlauth.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel='stylesheet' href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    {#    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>#}
    {#    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>#}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>

<header class="p-3 text-bg-info border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/7.jpg' %}" alt=" " height="40">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
                <li><a href="/blog/pub" class="nav-link px-2 text-white">粥粥</a></li>
                <li><a href="/blog/pub" class="nav-link px-2 text-white">薛定谔的猫</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
                <input type="search" class="form-control " placeholder="搜索..." aria-label="Search">
            </form>

            {% if user.is_authenticated %}
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'image/me.jpg' %}" alt="mdo" width="32" height="32"
                             class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="/auth/logout">退出登录</a></li>
                    </ul>
                </div>
                </div>
            {% else %}
                <div class="text-end">
                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                        <li><a href="/auth/login" class="btn btn-outline-light me-2">登录</a></li>
                        <li><a href="/auth/register" class="btn btn-warning">注册</a></li>
                    </ul>
                </div>
            {% endif %}


    </div>
    </div>
</header>
<main class="container bg-body p-3 rounded-3">
    {% block main %}{% endblock %}
</main>

</body>
</html>

templates/blog_detail.html
{% extends 'base.html' %}

{% block title %}博客详情{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'highlight/styles/github-dark.min.css' %}">
    <script src={% static 'highlight/highlight.min.js' %}></script>
{% endblock %}

{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2">
        <img src="{% static 'image/me.jpg' %}" alt="" height="40" class="rounded-circle">
        <span class="ms-2">{{ blog.author.username }}</span>
        <span class="ms-2">于</span>
        <span class="ms-2">{{ blog.pub_date }}</span> 发布
    </div>
    <hr>
    <div class="py-2">
        {{ blog.content | safe }}
    </div>
    <hr>
    {#    <div class="mt-2">#}
    {#        <h3>评论（10）:</h3>#}
    {#        <form action="" method="POST"></form>#}
    {#        <div class="mt-2">#}
    {#            <input type="text" class="form-control" placeholder="请输入祝福">#}
    {#        </div>#}
    {##}
    {#        <div class="text-end">#}
    {#            <button type="button" class="btn btn-success mt-2">发表</button>#}
    {#        </div>#}
    {#    </div>#}


    {#    <div>#}
    {#        <ul class="list-group list-group-flush">#}
    {#            <li class="list-group-item">#}
    {#                <div class="d-flex justify-content-between">#}
    {#                    <div class="user-info">#}
    {#                        <img src="{% static 'image/1.jpg' %}" alt=" " height="30" width="30">#}
    {#                        <span class="ms-2">嗨</span>#}
    {#                    </div>#}
    {##}
    {#                    <div class="create-time">2024.10.17 23:46</div>#}
    {##}
    {#                </div>#}
    {#            </li>#}
    {##}
    {#            <li class="list-group-item">祝福祝福哈哈哈哈</li>#}
    {#            <li class="list-group-item">99呀</li>#}
    {#            <li class="list-group-item">好甜呀</li>#}
    {#        </ul>#}
    {#    </div>#}
    <script>
        hljs.highlightAll()
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block title %}雪de私人空间{% endblock %}


{% block main %}
    <h1>提升自己de经历</h1>

    <div class="row row-cols-2 row-gap-3">
        {% for blog in blogs %}
            <div class="col">
                <div class="card text-center">
                    <div class="card-header">
                        <a href="{% url 'blog:blog_detail' blog_id=blog.id %}" class="card-title">{{ blog.title}}</a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-conteit">{{ blog.content | striptags | truncatechars:20 }}</h5>
                    </div>

                    <div class="card-footer text-body-secondary d-flex justify-content-between">
                        <div>
                            <img src="{% static 'image/me.jpg' %}" alt="" height="40" class="rounded-circle">
                            {{ blog.author.username }}
                        </div>

                        <div>
                            发布时间：{{ blog.pub_date }}
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}
















    {#    <div class="row row-cols-2 row-gap-3">#}
    {#        <div class="col">#}
    {#            <div class="card text-center">#}
    {#                <div class="card-header">#}
    {#                    事情一#}
    {#                </div>#}
    {#                <div class="card-body">#}
    {#                    <h5 class="card-title">抓娃娃</h5>#}
    {#                    <a href="#" class="btn btn-primary">Go somewhere</a>#}
    {#                </div>#}
    {##}
    {#                <div class="card-footer text-body-secondary d-flex justify-content-between">#}
    {#                    <div>#}
    {#                        <img src="{% static 'image/me.jpg' %}" alt="" height="40" class="rounded-circle">#}
    {#                        薛定谔的猫#}
    {#                    </div>#}
    {##}
    {#                    <div>#}
    {#                        7 days ago#}
    {#                    </div>#}
    {#                </div>#}
    {##}
    {#            </div>#}
    {#        </div>#}
    {##}
    {#        <div class="col">#}
    {#            <div class="card text-center">#}
    {#                <div class="card-header">#}
    {#                    事情二#}
    {#                </div>#}
    {#                <div class="card-body">#}
    {#                    <h5 class="card-title">看表演</h5>#}
    {#                    <a href="#" class="btn btn-primary">Go somewhere</a>#}
    {#                </div>#}
    {#                <div class="card-footer text-body-secondary d-flex justify-content-between">#}
    {#                    <div>#}
    {#                        <img src="{% static 'image/you.jpg' %}" alt="" height="40" class="rounded-circle">#}
    {#                        粥粥#}
    {#                    </div>#}
    {#                    <div>#}
    {#                        7 days ago#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {##}
    {#        <div class="col">#}
    {#            <div class="card text-center">#}
    {#                <div class="card-header">#}
    {#                    事情三#}
    {#                </div>#}
    {#                <div class="card-body">#}
    {#                    <h5 class="card-title">涂石膏娃娃</h5>#}
    {#                    <a href="#" class="btn btn-primary">Go somewhere</a>#}
    {#                </div>#}
    {#                <div class="card-footer text-body-secondary d-flex justify-content-between">#}
    {#                    <div>#}
    {#                        <img src="{% static 'image/you.jpg' %}" alt="" height="40" class="rounded-circle">#}
    {#                        粥粥#}
    {#                    </div>#}
    {#                    <div>#}
    {#                        7 days ago#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {##}
    {#        <div class="col">#}
    {#            <div class="card text-center">#}
    {#                <div class="card-header">#}
    {#                    事情四#}
    {#                </div>#}
    {#                <div class="card-body">#}
    {#                    <h5 class="card-title">牵手散步</h5>#}
    {#                    <a href="#" class="btn btn-primary">Go somewhere</a>#}
    {#                </div>#}
    {#                <div class="card-footer text-body-secondary d-flex justify-content-between">#}
    {#                    <div>#}
    {#                        <img src="{% static 'image/you.jpg' %}" alt="" height="40" class="rounded-circle">#}
    {#                        粥粥#}
    {#                    </div>#}
    {#                    <div>#}
    {#                        7 days ago#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {##}
    {#    </div>#}


{% endblock %}

templates/indexjingang.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主空间</title>
    <!-- 引入 Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="d-flex justify-content-center align-items-center bg-dark" style="height: 100vh;">

<div class="text-center text-white">
    <!-- 添加上边距 -->
    <a href="/jingang" class="btn btn-success btn-lg w-auto mb-4">进入主空间</a>

    <!-- 文本内容 -->
    <h3>Hello,你好呀小大人😃</h3>
    <h4>已经等你很久啦...😒</h4>
    <h4>最近过的怎么样呢😎</h4>
    <h4>有什么想分享告诉我的吗🤳</h4>
    <h4>但是无论你最近开不开心请你记住</h4>
    <h2 class="text-warning">永远不要因为打翻牛奶而哭泣</h2>
    <h5>可以把你想分享给我的事情进去主空间告诉我呀</h5>
</div>

</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block title %}请你登录{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js'%}"></script>
    <script src="{% static 'js/login.js' %}"></script>
{% endblock %}

{% block main %}
    <div style="max-width: 330px" class="m-auto">
        <h1>登录</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" placeholder="邮箱" class="form-control" name="email" property="邮箱">
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" placeholder="密码" class="form-control" name="password" property="密码">
            </div>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    记住我
                </label>
            </div>
            {% if form %}
                
            {% endif %}
            <div class="mb-3">
                <button class="btn btn-primary w-100" type="submit" id="login-btn">立即登录</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/pub_blog.html
{% extends 'base.html' %}

{% block title %}发布内容{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js'%}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'js/pub_blog.js' %}"></script>
    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
{% endblock %}

{% block main %}
    <h1>发布事情</h1>
    <div class="mt-3">
        <form action="" method="POST">
        {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>

            <div class="mb-3">
                <label class="form-label">分类</label>
                <select name="category" class="form-select">
                    {% for i in category %}
                        <option value="{{ i.id }}">{{ i.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mb-3">
                <label class="form-label">内容</label>
                <div id="editor—wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mb-3 text-end">
                <button class="btn btn-primary" id="submit-btn">发布</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block title %}请你注册{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js'%}"></script>
    <script src="{% static 'js/register.js'%}"></script>
{% endblock %}

{% block main %}
    <div style="max-width: 330px" class="m-auto">
        <h1>注册</h1>
        <form action="" method="POST">
            {% csrf_token %}
            <div class="mb-3">
                <label>用户名</label>
                <input type="text" class="form-control" name="username" property="用户名" placeholder="用户名">
            </div>
            <div class="mb-3">
                <label>邮箱</label>
                <input type="email" class="form-control" name="email" property="邮箱" placeholder="邮箱">
            </div>
            <div class="mb-3">
                <label>验证码</label>
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="captcha" placeholder="验证码"
                           aria-label="Recipient's username" aria-describedby="button-addon2">
                    <button class="btn btn-outline-secondary" type="button" id="button-addon2">获取验证码</button>
                </div>
            </div>
            <div class="mb-3">
                <label>密码</label>
                <input type="password" class="form-control" placeholder="密码" name="password" property="密码">
            </div>
            <div class="mb-3">
                <button class="btn btn-primary w-100" id="register_now" type="submit">立即注册</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/test2.html
{#{% extends "base.html" %}#}
{##}
{#{% block head %}#}
{#    <script src={% static "js/test2.js" %}></script>#}
{#{% endblock %}#}
{##}
{#{% block main %}#}
{#    <h1>啊哈哈哈哈</h1>#}
{#    <div class="d-grid gap-2 col-6 mx-auto">#}
{#        <button class="btn btn-primary w-10" id="test2-button">点击我！</button>#}
{#    </div>#}
{#{% endblock %}#}
{##}
{##}



{% extends "base.html" %}

{% block head %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'js/test2.js' %}"></script>
{% endblock %}

{% block main %}
    <h1>啊哈哈哈哈</h1>
    <div class="d-grid gap-2 col-6 mx-auto">
        <button class="btn btn-primary w-10" id="test2-button">点击我！</button>
    </div>
{% endblock %}